In [69]:
import json
import pandas as pd
import requests
import os
from configparser import ConfigParser
from datetime import datetime

from pathlib import Path

config= ConfigParser()

In [70]:
Url = "https://api.rawg.io/api/games?dates=2023-11-01,2023-12-31&key=7014133b1fb7416a849e8e13992b8d55"

In [71]:
# Consultamos el ingreso a la API

response = requests.get(Url)

if response.status_code == 200:
    data = response.json()

    games_df = pd.DataFrame(data['results'])
    print('Ingreso Exitoso')
    
else:
    print(f"Error: {response.status_code}")

Ingreso Exitoso

In [72]:
# Obtenemos el DF games, donde podremos observar sus datos

games_df.head()

# Ordenamos el df por la fecha de lanzamiento (Mas recientes a mas antiguos)

,slug,name,playtime,platforms,stores,released,tba,background_image,rating,rating_top,ratings,ratings_count,reviews_text_count,added,added_by_status,metacritic,suggestions_count,updated,id,score,clip,tags,esrb_rating,user_game,reviews_count,saturated_color,dominant_color,short_screenshots,parent_platforms,genres,community_rating
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,True,https://media.rawg.io/media/games/27c/27cd8b7d...,4.50,5,"[{'id': 5, 'title': 'exceptional', 'count': 28...",38,1,799,"{'yet': 97, 'owned': 84, 'beaten': 6, 'toplay'...",None,412,2023-12-01T09:48:20,292844,None,None,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...",None,None,40,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",NaN
1,replaced,Replaced,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,True,https://media.rawg.io/media/games/041/041e0418...,3.33,5,"[{'id': 5, 'title': 'exceptional', 'count': 3,...",9,0,439,"{'yet': 64, 'owned': 54, 'toplay': 321}",None,223,2023-08-26T09:06:27,616693,None,None,"[{'id': 32, 'name': 'Sci-fi', 'slug': 'sci-fi'...",None,None,9,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 83, 'name': 'Platformer', 'slug': 'pla...",NaN
2,the-day-before-2,The Day Before,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-08,False,https://media.rawg.io/media/games/d0b/d0bc26b4...,2.58,1,"[{'id': 1, 'title': 'skip', 'count': 15, 'perc...",26,0,271,"{'yet': 41, 'owned': 40, 'toplay': 187, 'dropp...",None,436,2023-12-05T15:40:45,681395,None,None,[],None,None,26,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 59, 'name': 'Massively Multiplayer', '...",NaN
3,robocop-rogue-city,RoboCop: Rogue City,5,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-11-02,False,https://media.rawg.io/media/games/2ae/2ae41504...,3.95,4,"[{'id': 4, 'title': 'recommended', 'count': 19...",38,1,264,"{'yet': 42, 'owned': 34, 'beaten': 27, 'toplay...",None,394,2023-12-05T19:06:20,631942,None,None,"[{'id': 31, 'name': 'Singleplayer', 'slug': 's...","{'id': 5, 'name': 'Adults Only', 'slug': 'adul...",None,41,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 3, 'name': 'Adventure', 'slug': 'adven...",NaN
4,avatar-frontiers-of-pandora,Avatar: Frontiers of Pandora,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 3, 'name': 'PlayStation Stor...",2023-12-07,False,https://media.rawg.io/media/games/983/9837c2e9...,3.17,4,"[{'id': 4, 'title': 'recommended', 'count': 3,...",6,0,259,"{'yet': 39, 'owned': 24, 'toplay': 196}",None,513,2023-12-04T02:02:40,616677,None,None,[],None,None,6,0f0f0f,0f0f0f,"[{'id': -1, 'image': 'https://media.rawg.io/me...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action'}]",NaN

In [73]:
games_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   slug                20 non-null     object
 1   name                20 non-null     object
 2   playtime            20 non-null     int64
 3   platforms           20 non-null     object
 4   stores              20 non-null     object
 5   released            20 non-null     object
 6   tba                 20 non-null     bool
 7   background_image    20 non-null     object
 8   rating              20 non-null     float64
 9   rating_top          20 non-null     int64
 10  ratings             20 non-null     object
 11  ratings_count       20 non-null     int64
 12  reviews_text_count  20 non-null     int64
 13  added               20 non-null     int64
 14  added_by_status     20 non-null     object
 15  metacritic          0 non-null      object
 16  suggestions_count   20 non-null     int64
 17  updated             20 non-null     object
 18  id                  20 non-null     int64
 19  score               0 non-null      object
 20  clip                0 non-null      object
 21  tags                20 non-null     object
 22  esrb_rating         6 non-null      object
 23  user_game           0 non-null      object
 24  reviews_count       20 non-null     int64
 25  saturated_color     20 non-null     object
 26  dominant_color      20 non-null     object
 27  short_screenshots   20 non-null     object
 28  parent_platforms    20 non-null     object
 29  genres              20 non-null     object
 30  community_rating    7 non-null      float64
dtypes: bool(1), float64(2), int64(8), object(20)
memory usage: 4.8+ KB

In [74]:
Columnas_Df=[ 
    'id',
    'slug',
    'name',
    'playtime',
    'platforms',
    'stores',
    'released',
    'rating',
    'rating_top',
    'updated',
    'esrb_rating',
    'parent_platforms',
    'genres'
]

games_df = games_df.drop(columns=games_df.columns.difference(Columnas_Df))
games_df.head()

,slug,name,playtime,platforms,stores,released,rating,rating_top,updated,id,esrb_rating,parent_platforms,genres
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},..."
1,replaced,Replaced,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,3.33,5,2023-08-26T09:06:27,616693,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 83, 'name': 'Platformer', 'slug': 'pla..."
2,the-day-before-2,The Day Before,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-08,2.58,1,2023-12-05T15:40:45,681395,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 59, 'name': 'Massively Multiplayer', '..."
3,robocop-rogue-city,RoboCop: Rogue City,5,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-11-02,3.95,4,2023-12-05T19:06:20,631942,"{'id': 5, 'name': 'Adults Only', 'slug': 'adul...","[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 3, 'name': 'Adventure', 'slug': 'adven..."
4,avatar-frontiers-of-pandora,Avatar: Frontiers of Pandora,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 3, 'name': 'PlayStation Stor...",2023-12-07,3.17,4,2023-12-04T02:02:40,616677,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 4, 'name': 'Action', 'slug': 'action'}]"

In [94]:
def extract_column_to_df(df, column_name):
    # Inicializar una lista para almacenar los diccionarios
    extracted_data = []

    # Iterar sobre las filas del DataFrame
    for _, row in df.iterrows():
        # Se extrae información de la columna especificada
        column_info = row[column_name]

        # Verificar si la columna contiene información válida antes de intentar agregar a la lista
        if isinstance(column_info, list) or isinstance(column_info, dict):
            extracted_data.extend(column_info if isinstance(column_info, list) else [column_info])

    # Crear un nuevo DataFrame con el nombre especificado
    new_df_name = f"{column_name}_df"
    globals()[new_df_name] = pd.DataFrame(extracted_data).drop_duplicates().set_index('id')


extract_column_to_df(games_df, 'genres')

In [92]:
# FUNCION PARA EXTRAER LAS 

def extract_and_merge(df, column,fila):

    # Lista para almacenar los diccionarios
    platforms_data = []

    # Iterar sobre las filas del DataFrame
    for _, row in df.iterrows():
        # Se extrae información de la columna especificada
        platforms_info = row[column]

        # Iterar sobre los diccionarios dentro de la lista (extraer y agregar a la lista)
        for platform_dict in platforms_info:
            platform_info = platform_dict[fila]
            platforms_data.append(platform_info)

    # Crear un nuevo DataFrame llamado "platforms_df"
    result_df = pd.DataFrame(platforms_data).drop_duplicates().set_index('id')

    return result_df



result_df = extract_and_merge(games_df, 'platforms','platform')
platforms_df= result_df

platforms_df

                name             slug
id
4                 PC               pc
7    Nintendo Switch  nintendo-switch
5              macOS            macos
6              Linux            linux
1           Xbox One         xbox-one
186  Xbox Series S/X    xbox-series-x
187    PlayStation 5     playstation5
18     PlayStation 4     playstation4

In [85]:
result_df = extract_and_merge(games_df, 'stores','store')
Store_df= result_df

Store_df

                 name               slug
id
1               Steam              steam
5                 GOG                gog
11         Epic Games         epic-games
3   PlayStation Store  playstation-store
2          Xbox Store         xbox-store
6      Nintendo Store           nintendo

In [49]:
# Lista para almacenar los diccionarios
platforms_data = []

# Iterar sobre las filas del df_games
for index, row in games_df.iterrows():
    # Se extrae información del diccionario en la celda
    platforms = row['platforms']
    
    # Itera sobre los diccionarios dentro de la lista (extrae y agrega a la lista)
    for platform_dict in platforms:
        platform_info = platform_dict['platform']
        platforms_data.append(platform_info)

# Nuevo DataFrame llamado "Plataforms"
Plataforms_df = pd.DataFrame(platforms_data)

Plataforms_df.drop_duplicates().set_index('id')

                name             slug
id
4                 PC               pc
7    Nintendo Switch  nintendo-switch
5              macOS            macos
6              Linux            linux
1           Xbox One         xbox-one
186  Xbox Series S/X    xbox-series-x
187    PlayStation 5     playstation5
18     PlayStation 4     playstation4

In [50]:
def extract_ids(platforms_list):
    return [platform['platform']['id'] for platform in platforms_list]

# Aplica la función a la columna 'platforms' y crear una nueva columna 'platform_ids'
games_df['platform_ids'] = games_df['platforms'].apply(extract_ids)

# Separa cada registro por las plataformas que esta disponible
games_df = games_df.explode('platform_ids')
games_df

# Imprimir el DataFrame resultante
games_df.head()

,slug,name,playtime,platforms,stores,released,rating,rating_top,updated,id,esrb_rating,parent_platforms,genres,platform_ids
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",4
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",7
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",5
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",6
1,replaced,Replaced,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,3.33,5,2023-08-26T09:06:27,616693,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 83, 'name': 'Platformer', 'slug': 'pla...",4

In [68]:
games_df['id_parent_platforms'] = games_df['platforms'].apply(extract_ids)
games_df.head()

,slug,name,playtime,platforms,stores,released,rating,rating_top,updated,id,esrb_rating,parent_platforms,genres,platform_ids,id_parent_platforms
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",4,"[4, 7, 5, 6]"
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",7,"[4, 7, 5, 6]"
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",5,"[4, 7, 5, 6]"
0,hollow-knight-silksong,Hollow Knight: Silksong,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,4.50,5,2023-12-01T09:48:20,292844,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 51, 'name': 'Indie', 'slug': 'indie'},...",6,"[4, 7, 5, 6]"
1,replaced,Replaced,0,"[{'platform': {'id': 4, 'name': 'PC', 'slug': ...","[{'store': {'id': 1, 'name': 'Steam', 'slug': ...",2023-12-31,3.33,5,2023-08-26T09:06:27,616693,None,"[{'platform': {'id': 1, 'name': 'PC', 'slug': ...","[{'id': 83, 'name': 'Platformer', 'slug': 'pla...",4,"[4, 1, 186]"

In [66]:
platforms_data = []

# Iterar sobre las filas del DataFrame
for index, row in games_df.iterrows():
    # Se extrae información de la columna 'parent_platforms'
    parent_platforms = row['parent_platforms']
    
    # Iterar sobre los diccionarios dentro de la lista (extraer y agregar a la lista)
    for platform_dict in parent_platforms:
        platform_info = platform_dict['platform']
        platforms_data.append(platform_info)

# Crear un nuevo DataFrame llamado "platforms_df"
platforms_df = pd.DataFrame(platforms_data).drop_duplicates(subset='id')

platforms_df.set_index('id', inplace=True)

platforms_df

               name         slug
id
1                PC           pc
5   Apple Macintosh          mac
6             Linux        linux
7          Nintendo     nintendo
3              Xbox         xbox
2       PlayStation  playstation